### ISSUE TITLE
add wget-like command in ZOS

### ISSUE THREAD

**Issue by usarana** [ProjectZ-Organization/ZFX#10]

**Comment by bumbelbee777** [comment]
pretty sure ZOS has something similar to that and shouldn't that be in the ZOS repository?

**Comment by usarana** [comment]
theres a curl command, not very similar

**Comment by usarana** [comment]
and also, yeah the issue is supposed to be in zos, i was just too lazy lol

**Comment by usarana** [comment]
this will also not be worked on (yet), see #9

**Comment by usarana** [comment]
oops
