### ISSUE TITLE
make the code cleaner

### ISSUE THREAD

**Issue by bumbelbee777** [ProjectZ-Organization/ZFX#14]
having the CPU, RAM and built-in firmware in the CPU file isn't a good idea...

**Comment by usarana** [comment]
is it? i feel like it's fine for now
anyways, i'm not working on the project right now so if you have any ideas just submit a pull request, ill accept every single one and review them after i'm back

**Comment by bumbelbee777** [comment]
yeah, since like having a 500 to even like 1000 lines of code in the future isn't nice, especially when fixing errors and/or bugs, and most of CPU.cs is dedicated to the RAM
